Update scrolling and replace supabase client with Prisma
GiG2Hire/gig-protocol pull request #44
Opened 2024-09-15 21:02 UTC by alhonaut

2024-09-21 08:12 UTC, mgroovyank requested changes

2024-09-21 11:54 UTC, mgroovyank commented on package.json
> +    "react-intersection-observer": "^9.13.1",
use pagination

2024-09-21 11:55 UTC, mgroovyank commented on package.json
> +    "react-intersection-observer": "^9.13.1",
After scrolling 50 offers, pagination should be there.

2024-09-24 16:51 UTC, mgroovyank approved these changes

2024-09-24 17:24 UTC, Horlarmmy approved these changes

2024-09-24 17:27 UTC, merged